CREATE TABLE cost_scenario (
    id                               BIGSERIAL PRIMARY KEY,
    public_id                        UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    organization_id                 BIGINT NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    quote_id                        BIGINT NOT NULL REFERENCES supplier_quote(id) ON DELETE RESTRICT,
    product_id                      BIGINT NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    previous_scenario_id            BIGINT UNIQUE REFERENCES cost_scenario(id) ON DELETE RESTRICT,
    revision_number                 INTEGER NOT NULL DEFAULT 1 CHECK (revision_number > 0),
    scenario_name                   VARCHAR(200) NOT NULL,

    quote_revision_number           INTEGER NOT NULL CHECK (quote_revision_number > 0),
    quote_currency                  VARCHAR(3) NOT NULL CHECK (quote_currency = upper(quote_currency)),
    quoted_unit_price               NUMERIC(19,4) CHECK (quoted_unit_price IS NULL OR quoted_unit_price >= 0),
    quoted_unit_price_source        TEXT CHECK (quoted_unit_price_source IN ('SUPPLIER_QUOTE','USER_ASSUMPTION','MARKET_REFERENCE','PROFESSIONAL_CONFIRMATION')),
    order_quantity                  NUMERIC(19,6) NOT NULL CHECK (order_quantity > 0),
    excluded_quantity               NUMERIC(19,6) NOT NULL CHECK (excluded_quantity >= 0 AND excluded_quantity < order_quantity),
    exchange_rate                   NUMERIC(19,6) CHECK (exchange_rate IS NULL OR exchange_rate > 0),
    exchange_rate_source            TEXT CHECK (exchange_rate_source IN ('SUPPLIER_QUOTE','USER_ASSUMPTION','MARKET_REFERENCE','PROFESSIONAL_CONFIRMATION')),
    taxable_freight_krw             NUMERIC(19,2) CHECK (taxable_freight_krw IS NULL OR taxable_freight_krw >= 0),
    customs_clearance_cost_krw      NUMERIC(19,2) CHECK (customs_clearance_cost_krw IS NULL OR customs_clearance_cost_krw >= 0),
    inspection_cost_krw             NUMERIC(19,2) CHECK (inspection_cost_krw IS NULL OR inspection_cost_krw >= 0),
    warehouse_cost_krw              NUMERIC(19,2) CHECK (warehouse_cost_krw IS NULL OR warehouse_cost_krw >= 0),
    domestic_delivery_cost_krw      NUMERIC(19,2) CHECK (domestic_delivery_cost_krw IS NULL OR domestic_delivery_cost_krw >= 0),
    other_cost_krw                  NUMERIC(19,2) CHECK (other_cost_krw IS NULL OR other_cost_krw >= 0),
    logistics_cost_source           TEXT CHECK (logistics_cost_source IN ('SUPPLIER_QUOTE','USER_ASSUMPTION','MARKET_REFERENCE','PROFESSIONAL_CONFIRMATION')),
    customs_duty_rate               NUMERIC(9,6) CHECK (customs_duty_rate IS NULL OR customs_duty_rate BETWEEN 0 AND 100),
    vat_rate                        NUMERIC(9,6) CHECK (vat_rate IS NULL OR vat_rate BETWEEN 0 AND 100),
    tax_rate_source                 TEXT CHECK (tax_rate_source IN ('SUPPLIER_QUOTE','USER_ASSUMPTION','MARKET_REFERENCE','PROFESSIONAL_CONFIRMATION')),
    vat_treatment                   TEXT NOT NULL CHECK (vat_treatment IN ('CASH_COST_INCLUDED','RECOVERABLE_EXCLUDED')),
    target_selling_price_krw        NUMERIC(19,2) CHECK (target_selling_price_krw IS NULL OR target_selling_price_krw >= 0),
    selling_fee_rate                NUMERIC(9,6) CHECK (selling_fee_rate IS NULL OR selling_fee_rate BETWEEN 0 AND 100),
    variable_cost_per_unit_krw      NUMERIC(19,2) CHECK (variable_cost_per_unit_krw IS NULL OR variable_cost_per_unit_krw >= 0),
    sales_assumption_source         TEXT CHECK (sales_assumption_source IN ('SUPPLIER_QUOTE','USER_ASSUMPTION','MARKET_REFERENCE','PROFESSIONAL_CONFIRMATION')),

    calculation_rule_version        TEXT NOT NULL,
    calculation_status              TEXT NOT NULL CHECK (calculation_status IN ('INCOMPLETE','COST_COMPLETE','COMPLETE')),
    sellable_quantity               NUMERIC(19,6) NOT NULL CHECK (sellable_quantity > 0),
    product_amount_quote_currency   NUMERIC(19,4),
    product_amount_krw              NUMERIC(19,2),
    taxable_value_krw               NUMERIC(19,2),
    customs_duty_krw                NUMERIC(19,2),
    vat_krw                         NUMERIC(19,2),
    total_cash_required_krw         NUMERIC(19,2),
    total_landed_cost_krw           NUMERIC(19,2),
    unit_landed_cost_krw            NUMERIC(19,2),
    selling_fee_per_unit_krw        NUMERIC(19,2),
    contribution_margin_per_unit_krw NUMERIC(19,2),
    created_by                      BIGINT NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    created_at                      TIMESTAMP NOT NULL DEFAULT NOW(),

    CHECK ((quoted_unit_price IS NULL) = (quoted_unit_price_source IS NULL)),
    CHECK ((exchange_rate IS NULL) = (exchange_rate_source IS NULL)),
    CHECK (calculation_status <> 'INCOMPLETE' OR total_landed_cost_krw IS NULL),
    CHECK (calculation_status = 'INCOMPLETE' OR unit_landed_cost_krw IS NOT NULL),
    CHECK (calculation_status <> 'COMPLETE' OR contribution_margin_per_unit_krw IS NOT NULL)
);

CREATE INDEX idx_cost_scenario_board ON cost_scenario(organization_id, created_at DESC);
CREATE INDEX idx_cost_scenario_product ON cost_scenario(organization_id, product_id, created_at DESC);
